# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'tdd-practice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tdd-practice
 pod "Quick"
 pod "Nimble"
 pod 'RxSwift'
 pod 'RxCocoa'

end

target 'tdd-practiceTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tdd-practice
 pod "Quick"
 pod "Nimble"
 pod 'RxTest'
 pod 'RxBlocking'
 pod 'Mockingjay'

end
